# Railway Monorepo Configuration

# This file defines multiple services in the monorepo
# Each service can be deployed independently

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "echo 'This is a monorepo. Deploy backend and frontend separately.'"
