[phases.setup]
nixPkgs = ["python310", "postgresql"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn run:app --bind 0.0.0.0:$PORT"
